### PR TITLE
Clean up of Readme

### PR DESCRIPTION
**Pull request by ghost**
Ubuntu does not identify itself as "Ubuntu Linux" as such I have removed the reference and left plain "Ubuntu" as to reduce confusion and keep consistency.

### CODE REVIEW

**Comment by RS102839** [comment]
My concern may be that while Ubuntu prefer to be just Ubuntu, adding "Linux" serves people who may not be familiar with Ubuntu.

**Comment by ghost** [comment]
If they do a Google Search for "Ubuntu" it will come up... I do not think it will confuse those who are not familiar an in reality I believe that the target of this source package is developers and I have yet to meet a developer who was not familiar with what Ubuntu is.

**Comment by MIfeanyi** [comment]
I dont see the Linux part causing confusing.

**Comment by ghost** [comment]
Its much like calling "Android" "Android Linux" if were going to call it "Ubuntu Linux" then why not "Ubuntu GNU/Linux"?

**Comment by RS102839** [comment]
I'll take that under advisement  :-)

We are trying to use "Ubuntu Linux" as shorthand for something like "the well known distribution of Linux from Ubuntu".
Your point is valid and perhaps all the people who find their way to GitHub already know what Ubuntu is, but I'm often amazed when people don't know what appears obvious.

**Comment by RS102839** [comment]
I recommend moving this discussion to the forums.

**Pull request closed without merging**
